/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Control.ControlKembali;

import Model.ModelKembali;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author LENOVO
 */
public class ViewKembali extends javax.swing.JFrame {

    /**
     * Creates new form ViewKembali
     */
    public ViewKembali() {
        initComponents();
        ViewDataKembali();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePengembalian = new javax.swing.JTable();
        NopinjamTFK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TanggalkembaliTFK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        StatusTFK = new javax.swing.JTextField();
        BtnupdateK = new javax.swing.JButton();
        BtnkembaliK = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TotalDendaTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel10.setText("PENGEMBALIAN BUKU");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NO PINJAM");

        TablePengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TablePengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePengembalian);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("TANGGAL KEMBALI");

        TanggalkembaliTFK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalkembaliTFKActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("STATUS");

        BtnupdateK.setText("Update");
        BtnupdateK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnupdateKActionPerformed(evt);
            }
        });

        BtnkembaliK.setText("Kembali");
        BtnkembaliK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkembaliKActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("TOTAL DENDA");

        TotalDendaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDendaTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NopinjamTFK, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnupdateK))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TotalDendaTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TanggalkembaliTFK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(StatusTFK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(337, 355, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(BtnkembaliK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel10)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NopinjamTFK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnupdateK))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(StatusTFK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(TotalDendaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(TanggalkembaliTFK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnkembaliK))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addContainerGap(801, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(186, 186, 186)
                .addComponent(jLabel7)
                .addGap(209, 209, 209))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablePengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePengembalianMouseClicked
        int baris = TablePengembalian.getSelectedRow();
        if (baris < 20){
            NopinjamTFK.setText(TablePengembalian.getValueAt(baris,0).toString());
            StatusTFK.setText(TablePengembalian.getValueAt(baris,5).toString());
            TanggalkembaliTFK.setText(TablePengembalian.getValueAt(baris,4).toString());
        }
        
        String tglKembali = TablePengembalian.getValueAt(baris,4).toString();
        String tglPinjam = TablePengembalian.getValueAt(baris,1).toString();
        hitungDenda(tglKembali, tglPinjam);
        TotalDendaTF.setText(String.valueOf(hitungDenda(tglKembali, tglPinjam)));
    }//GEN-LAST:event_TablePengembalianMouseClicked

    private void BtnkembaliKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkembaliKActionPerformed
        View.ViewMenuHome homePage = new View.ViewMenuHome();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnkembaliKActionPerformed

    private void TanggalkembaliTFKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalkembaliTFKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalkembaliTFKActionPerformed

    private void BtnupdateKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnupdateKActionPerformed
          try {
            ModelKembali tb = new ModelKembali();
            
            tb.setNopinjam(NopinjamTFK.getText());
            tb.setTanggalkembali(TanggalkembaliTFK.getText());
            tb.setStatus(StatusTFK.getText());
        
        if (NopinjamTFK.getText().isEmpty() || TanggalkembaliTFK.getText().isEmpty() || StatusTFK.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);            
        } else {
            ControlKembali k = new ControlKembali();
            k.Update(tb);
            ViewDataKembali();
        } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi untuk simpan"+e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnupdateKActionPerformed

    private void TotalDendaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDendaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalDendaTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKembali().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnkembaliK;
    private javax.swing.JButton BtnupdateK;
    private javax.swing.JTextField NopinjamTFK;
    private javax.swing.JTextField StatusTFK;
    private javax.swing.JTable TablePengembalian;
    private javax.swing.JTextField TanggalkembaliTFK;
    private javax.swing.JTextField TotalDendaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void ViewDataKembali() {
    DefaultTableModel tpeg = new DefaultTableModel();
    
    tpeg.addColumn("no_pinjam");
    tpeg.addColumn("tanggal_pinjam");    
    tpeg.addColumn("id_user");
    tpeg.addColumn("kode_buku");
    tpeg.addColumn("tanggal_kembali");
    tpeg.addColumn("status");


    Connection connn = null;
    Statement stat = null;
    ResultSet rs = null;

    try {
        connn = Conection.Connection.getConnection();
        String sql = "SELECT * FROM tb_peminjaman";
        stat = connn.createStatement();
        rs = stat.executeQuery(sql);

        while (rs.next()) {
            tpeg.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6)});
        }

        TablePengembalian.setModel(tpeg);
    } catch (SQLException e) {
        System.out.println("Error: " + e.getMessage());
    } finally {
        // Pastikan untuk menutup ResultSet, Statement, dan Connection
        if (rs != null) {
            try {
                rs.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        if (stat != null) {
            try {
                stat.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        if (connn != null) {
            try {
                connn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}

public int hitungDenda(String tanggalPinjam, String tanggalKembali){
    LocalDate tglKembali = LocalDate.parse(tanggalKembali);
    LocalDate tglPinjam = LocalDate.parse(tanggalPinjam);

    long selisihHari = ChronoUnit.DAYS.between(tglKembali, tglPinjam);

    if (selisihHari > 30){
        return (int) ((selisihHari - 30) * 5000); 
    } else{
        return 0;   
    }
}

}
