/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.sql.SQLException;
import Control.ControlUserData;
import Model.ModelUserData;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class ViewUserData extends javax.swing.JFrame {

    /**
     * Creates new form ViewBuku
     */
    public ViewUserData() {
        initComponents();
        ViewDataUser();
        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDUserTF = new javax.swing.JTextField();
        PasswordUserTF = new javax.swing.JTextField();
        NamaUserTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NoHpTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EmailTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AlamatTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TglLahirTF = new javax.swing.JTextField();
        BtnTambah = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JenisKelaminCB = new javax.swing.JComboBox<>();
        RoleCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID USER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD USER");

        IDUserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDUserTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("NAMA USER");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("JENIS KELAMIN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("NO HP");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("EMAIL");

        EmailTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("ALAMAT");

        AlamatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatTFActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("TGL LAHIR");

        TglLahirTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TglLahirTFActionPerformed(evt);
            }
        });

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnKembali.setText("Kembali");
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableUser);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Data User Perpustakaan");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("ROLE");

        JenisKelaminCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        JenisKelaminCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKelaminCBActionPerformed(evt);
            }
        });

        RoleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa", "Dosen", "Petugas" }));
        RoleCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleCBActionPerformed(evt);
            }
        });

        jLabel10.setText("(YYYY-MM-DD)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JenisKelaminCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDUserTF)
                                    .addComponent(PasswordUserTF)
                                    .addComponent(NamaUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NoHpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AlamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(37, 37, 37))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addGap(75, 75, 75)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(RoleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TglLahirTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(BtnTambah)
                                                .addGap(18, 18, 18)
                                                .addComponent(BtnReset))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(BtnUpdate)
                                                .addGap(18, 18, 18)
                                                .addComponent(BtnDelete))
                                            .addComponent(BtnKembali)))
                                    .addComponent(jLabel10))))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AlamatTF, EmailTF, IDUserTF, NamaUserTF, NoHpTF, PasswordUserTF, TglLahirTF});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PasswordUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamaUserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JenisKelaminCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(NoHpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnTambah)
                                    .addComponent(BtnReset))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnUpdate)
                                    .addComponent(BtnDelete)))
                            .addComponent(AlamatTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TglLahirTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(RoleCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnKembali))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EmailTF, IDUserTF, NamaUserTF, NoHpTF, PasswordUserTF, TglLahirTF});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDUserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDUserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDUserTFActionPerformed

    private void AlamatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatTFActionPerformed

    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        int baris = TableUser.getSelectedRow();
        if (baris < 20){
            IDUserTF.setText(TableUser.getValueAt(baris,0).toString());
            PasswordUserTF.setText(TableUser.getValueAt(baris,1).toString());
            NamaUserTF.setText(TableUser.getValueAt(baris,2).toString());
            JenisKelaminCB.setSelectedItem(TableUser.getValueAt(baris,3).toString());
            NoHpTF.setText(TableUser.getValueAt(baris,4).toString());
            EmailTF.setText(TableUser.getValueAt(baris,5).toString());
            AlamatTF.setText(TableUser.getValueAt(baris,6).toString());
            TglLahirTF.setText(TableUser.getValueAt(baris,7).toString());
            RoleCB.setSelectedItem(TableUser.getValueAt(baris,8).toString());
        }
        IDUserTF.disable();
        BtnTambah.setEnabled(false);
        BtnReset.setEnabled(true);
        BtnDelete.setEnabled(true);
        BtnUpdate.setEnabled(true);
    }//GEN-LAST:event_TableUserMouseClicked

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        try {
            ModelUserData tb = new ModelUserData();
            tb.setId_user(IDUserTF.getText());
            tb.setPassword(PasswordUserTF.getText());
            tb.setNama_user(NamaUserTF.getText());
            tb.setJenis_kelamin_user(JenisKelaminCB.getSelectedItem().toString());
            tb.setNo_hp_user(NoHpTF.getText());
            tb.setEmail_user(EmailTF.getText());
            tb.setAlamat_user(AlamatTF.getText());
            tb.setTanggal_lahir_user(TglLahirTF.getText());
            tb.setRole(RoleCB.getSelectedItem().toString());
        
        if (IDUserTF.getText().equals("") || PasswordUserTF.getText().equals("") || NamaUserTF.getText().equals("")||
                JenisKelaminCB.getSelectedItem().equals("") || NoHpTF.getText().equals("") || EmailTF.getText().equals("")||
                AlamatTF.getText().equals("") || TglLahirTF.getText().equals("") || RoleCB.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);            
        } else {
            ControlUserData u = new ControlUserData();
            u.tambah(tb);
            Reset();
            ViewDataUser();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi untuk simpan"+e, "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        View.ViewMenuHome homePage = new View.ViewMenuHome();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void TglLahirTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TglLahirTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TglLahirTFActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try {
            ModelUserData tb = new ModelUserData();
            tb.setId_user(IDUserTF.getText());
            tb.setPassword(PasswordUserTF.getText());
            tb.setNama_user(NamaUserTF.getText());
            tb.setJenis_kelamin_user(JenisKelaminCB.getSelectedItem().toString());
            tb.setNo_hp_user(NoHpTF.getText());
            tb.setEmail_user(EmailTF.getText());
            tb.setAlamat_user(AlamatTF.getText());
            tb.setTanggal_lahir_user(TglLahirTF.getText());
            tb.setRole(RoleCB.getSelectedItem().toString());
        
        if (IDUserTF.getText().equals("") || PasswordUserTF.getText().equals("") || NamaUserTF.getText().equals("")||
                JenisKelaminCB.getSelectedItem().equals("") || NoHpTF.getText().equals("") || EmailTF.getText().equals("")||
                AlamatTF.getText().equals("") || TglLahirTF.getText().equals("") || RoleCB.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);            
        } else {
            ControlUserData u = new ControlUserData();
            u.update(tb, tb.getId_user());
            Reset();
            ViewDataUser();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi untuk simpan"+e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        try {
            ModelUserData tb = new ModelUserData();
            tb.setId_user(IDUserTF.getText());
            tb.setPassword(PasswordUserTF.getText());
            tb.setNama_user(NamaUserTF.getText());
            tb.setJenis_kelamin_user(JenisKelaminCB.getSelectedItem().toString());
            tb.setNo_hp_user(NoHpTF.getText());
            tb.setEmail_user(EmailTF.getText());
            tb.setAlamat_user(AlamatTF.getText());
            tb.setTanggal_lahir_user(TglLahirTF.getText());
            tb.setRole(RoleCB.getSelectedItem().toString());
        
        if (IDUserTF.getText().equals("") || PasswordUserTF.getText().equals("") || NamaUserTF.getText().equals("")||
                JenisKelaminCB.getSelectedItem().equals("") || NoHpTF.getText().equals("") || EmailTF.getText().equals("")||
                AlamatTF.getText().equals("") || TglLahirTF.getText().equals("") || RoleCB.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);            
        } else {
            ControlUserData u = new ControlUserData();
            u.delete(tb.getId_user());
            Reset();
            ViewDataUser();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi untuk simpan"+e, "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        IDUserTF.setEnabled(true);
        Reset();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void JenisKelaminCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKelaminCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisKelaminCBActionPerformed

    private void RoleCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoleCBActionPerformed

    private void EmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUserData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatTF;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField IDUserTF;
    private javax.swing.JComboBox<String> JenisKelaminCB;
    private javax.swing.JTextField NamaUserTF;
    private javax.swing.JTextField NoHpTF;
    private javax.swing.JTextField PasswordUserTF;
    private javax.swing.JComboBox<String> RoleCB;
    private javax.swing.JTable TableUser;
    private javax.swing.JTextField TglLahirTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void ViewDataUser(){
    DefaultTableModel tpeg = new DefaultTableModel();
    tpeg.addColumn("id_user");
    tpeg.addColumn("password_user");
    tpeg.addColumn("nama_user");
    tpeg.addColumn("jenis_kelamin_user");
    tpeg.addColumn("no_hp_user");
    tpeg.addColumn("email_user");
    tpeg.addColumn("alamat_user");
    tpeg.addColumn("tanggal_lahir_user");
    tpeg.addColumn("role");
    
    
    try {
        Connection con = Conection.Connection.getConnection();
        String sql = "Select * from tb_user";
        Statement stat = con.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()){
            tpeg.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6),
            rs.getString(7),
            rs.getDate(8),
            rs.getString(9)});
        }
        TableUser.setModel(tpeg);
    } catch (SQLException e) {
        System.out.println("Error");
    }    
}

private void Reset(){
    BtnReset.setEnabled(true);
    BtnTambah.setEnabled(true);    
    BtnKembali.setEnabled(true);
    NamaUserTF.setText("");
    PasswordUserTF.setText("");
    IDUserTF.setText("");
    NoHpTF.setText("");
    TglLahirTF.setText("");
    AlamatTF.setText("");
    EmailTF.setText("");
    BtnDelete.setEnabled(false);
    BtnUpdate.setEnabled(false);
}
}
