/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControlBuku;
import Model.ModelBuku;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class ViewBuku extends javax.swing.JFrame {

    /**
     * Creates new form ViewBuku
     */
    public ViewBuku() {
        initComponents();
        ViewDataBuku();
        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KodeBukuTF = new javax.swing.JTextField();
        JudulbukuTF = new javax.swing.JTextField();
        JenisbukuTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PengarangTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PenerbitTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TahunTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        StokbukuTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RakbukuTF = new javax.swing.JTextField();
        BtnTambah = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBukuPetugas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("KODE BUKU");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("JUDUL BUKU");

        KodeBukuTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeBukuTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("JENIS BUKU");

        PengarangTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengarangTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("PENGARANG");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("PENERBIT");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("TAHUN");

        TahunTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("STOK BUKU");

        StokbukuTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokbukuTFActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("RAK BUKU");

        RakbukuTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RakbukuTFActionPerformed(evt);
            }
        });

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnKembali.setText("Kembali");
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        TableBukuPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        TableBukuPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBukuPetugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBukuPetugas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Data Buku Perpustakaan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(733, 733, 733))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PengarangTF, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(KodeBukuTF)
                    .addComponent(JudulbukuTF)
                    .addComponent(JenisbukuTF))
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RakbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TahunTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PenerbitTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(StokbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(BtnReset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnKembali)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KodeBukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(PenerbitTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JudulbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(TahunTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(JenisbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StokbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PengarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(RakbukuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTambah)
                            .addComponent(BtnReset))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnUpdate)
                            .addComponent(BtnDelete))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnKembali)
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KodeBukuTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeBukuTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeBukuTFActionPerformed

    private void PengarangTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengarangTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PengarangTFActionPerformed

    private void StokbukuTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokbukuTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StokbukuTFActionPerformed

    private void TableBukuPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBukuPetugasMouseClicked
        // TODO add your handling code here:
        int baris = TableBukuPetugas.getSelectedRow();
        if (baris < 20){
            KodeBukuTF.setText(TableBukuPetugas.getValueAt(baris,0).toString());
            JudulbukuTF.setText(TableBukuPetugas.getValueAt(baris,1).toString());
            JenisbukuTF.setText(TableBukuPetugas.getValueAt(baris,2).toString());
            PengarangTF.setText(TableBukuPetugas.getValueAt(baris,3).toString());
            PenerbitTF.setText(TableBukuPetugas.getValueAt(baris,4).toString());
            TahunTF.setText(TableBukuPetugas.getValueAt(baris,5).toString());
            StokbukuTF.setText(TableBukuPetugas.getValueAt(baris,6).toString());
            RakbukuTF.setText(TableBukuPetugas.getValueAt(baris,7).toString());
        }
        KodeBukuTF.disable();
        BtnTambah.setEnabled(false);
        BtnReset.setEnabled(true);
        BtnDelete.setEnabled(true);
        BtnUpdate.setEnabled(true);
    
    }//GEN-LAST:event_TableBukuPetugasMouseClicked

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
         try {
            ModelBuku tb = new ModelBuku();
            tb.setKode_buku(KodeBukuTF.getText());
            tb.setJudul_buku(JudulbukuTF.getText());
            tb.setJenis_buku(JenisbukuTF.getText());
            tb.setPengarang(PengarangTF.getText());
            tb.setPenerbit(PenerbitTF.getText());
            tb.setTahun(TahunTF.getText());
            tb.setStok_buku(StokbukuTF.getText());
            tb.setRak_buku(RakbukuTF.getText());
        
        if (KodeBukuTF.getText().equals("") || JudulbukuTF.getText().equals("") || JenisbukuTF.getText().equals("")||
                PengarangTF.getText().equals("") || PenerbitTF.getText().equals("") || TahunTF.getText().equals("")||
                StokbukuTF.getText().equals("") || RakbukuTF.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);            
        } else {
            ControlBuku u = new ControlBuku();
            u.tambah(tb);
            Reset();
            ViewDataBuku();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi untuk simpan"+e, "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        View.ViewMenuHome homePage = new View.ViewMenuHome();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void RakbukuTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RakbukuTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RakbukuTFActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
         try {
            ModelBuku tb = new ModelBuku();
            tb.setKode_buku(KodeBukuTF.getText());
            tb.setJudul_buku(JudulbukuTF.getText());
            tb.setJenis_buku(JenisbukuTF.getText());
            tb.setPengarang(PengarangTF.getText());
            tb.setPenerbit(PenerbitTF.getText());
            tb.setTahun(TahunTF.getText());
            tb.setStok_buku(StokbukuTF.getText());
            tb.setRak_buku(RakbukuTF.getText());
        
        if (KodeBukuTF.getText().equals("") || JudulbukuTF.getText().equals("") || JenisbukuTF.getText().equals("")||
                PengarangTF.getText().equals("") || PenerbitTF.getText().equals("") || TahunTF.getText().equals("")||
                StokbukuTF.getText().equals("") || RakbukuTF.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);            
        } else {
            ControlBuku u = new ControlBuku();
            u.update(tb, tb.getKode_buku());
            Reset();
            ViewDataBuku();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi untuk simpan"+e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            ModelBuku tb = new ModelBuku();
            tb.setKode_buku(KodeBukuTF.getText());
            tb.setJudul_buku(JudulbukuTF.getText());
            tb.setJenis_buku(JenisbukuTF.getText());
            tb.setPengarang(PengarangTF.getText());
            tb.setPenerbit(PenerbitTF.getText());
            tb.setTahun(TahunTF.getText());
            tb.setStok_buku(StokbukuTF.getText());
            tb.setRak_buku(RakbukuTF.getText());
        
        if (KodeBukuTF.getText().equals("") || JudulbukuTF.getText().equals("") || JenisbukuTF.getText().equals("")||
                PengarangTF.getText().equals("") || PenerbitTF.getText().equals("") || TahunTF.getText().equals("")||
                StokbukuTF.getText().equals("") || RakbukuTF.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);            
        } else {
            ControlBuku u = new ControlBuku();
            u.delete(tb.getKode_buku());
            Reset();
            ViewDataBuku();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal koneksi untuk simpan"+e, "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        KodeBukuTF.setEnabled(true);
        Reset();
    }//GEN-LAST:event_BtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField JenisbukuTF;
    private javax.swing.JTextField JudulbukuTF;
    private javax.swing.JTextField KodeBukuTF;
    private javax.swing.JTextField PenerbitTF;
    private javax.swing.JTextField PengarangTF;
    private javax.swing.JTextField RakbukuTF;
    private javax.swing.JTextField StokbukuTF;
    private javax.swing.JTable TableBukuPetugas;
    private javax.swing.JTextField TahunTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void ViewDataBuku(){
    DefaultTableModel tpeg = new DefaultTableModel();
    tpeg.addColumn("kode_buku");
    tpeg.addColumn("judul_buku");
    tpeg.addColumn("jenis_buku");
    tpeg.addColumn("pengarang");
    tpeg.addColumn("penerbit");
    tpeg.addColumn("tahun");
    tpeg.addColumn("stok_buku");
    tpeg.addColumn("rak_buku");
    
    
    try {
        Connection con = Conection.Connection.getConnection();
        String sql = "Select * from tb_buku";
        Statement stat = con.createStatement();
        ResultSet rs = stat.executeQuery(sql);
        while (rs.next()){
            tpeg.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6),
            rs.getString(7),
            rs.getString(8)});
        }
        TableBukuPetugas.setModel(tpeg);
    } catch (SQLException e) {
        System.out.println("Error");
    }    
}

private void Reset(){
    BtnReset.setEnabled(true);
    BtnTambah.setEnabled(true);    
    BtnKembali.setEnabled(true);
    JenisbukuTF.setText("");
    JudulbukuTF.setText("");
    KodeBukuTF.setText("");
    PenerbitTF.setText("");
    PengarangTF.setText("");
    RakbukuTF.setText("");
    StokbukuTF.setText("");
    TahunTF.setText("");
    BtnDelete.setEnabled(false);
    BtnUpdate.setEnabled(false);
}

}
